In [3]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [5]:
A = np.array([1, 2, 3])

In [8]:
for e in L:
    print(e)

1
2
3


In [9]:
for a in A:
    print(a)

1
2
3


In [10]:
L.append(4)

In [11]:
L

[1, 2, 3, 4]

In [12]:
L + [5]

[1, 2, 3, 4, 5]

In [13]:
A + np.array([4])

array([5, 6, 7])

In [14]:
A

array([1, 2, 3])

In [15]:
A + np.array([4, 5 ,6])

array([5, 7, 9])

In [16]:
2 * A

array([2, 4, 6])

In [17]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
L2 = [e + 3 for e in L]

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [21]:
A**2

array([1, 4, 9])